# Generated by Django 3.1.3 on 2021-01-06 04:26

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210104_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_day',
            field=models.CharField(max_length=8, validators=[accounts.validators.validate_isdigit], verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[accounts.validators.validate_isdigit], verbose_name='전화번호'),
        ),
    ]
