# Generated by Django 3.1.3 on 2021-01-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='이름'),
            preserve_default=False,
        ),
    ]
